import { useEffect, useState } from "react";
import { Milestone, QuizQuestion, api } from "../lib/api";

type CheckpointQuizProps = {
  isOpen: boolean;
  onClose: () => void;
  token: string;
  roadmapId: string;
  milestone: Milestone;
  onAdaptResult: (changeSummary: string, changed: boolean) => void;
};

export default function CheckpointQuiz({
  isOpen,
  onClose,
  token,
  roadmapId,
  milestone,
  onAdaptResult,
}: CheckpointQuizProps) {
  const [step, setStep] = useState<"intro" | "questions" | "results" | "adapting">("intro");
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Real, topic-specific questions generated by mentor_ai_engine — fetched
  // once when the modal opens, not faked client-side.
  const [questions, setQuestions] = useState<QuizQuestion[]>([]);
  const [isLoadingQuestions, setIsLoadingQuestions] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  const topicTitleById = new Map(milestone.topics.map((t) => [t.topic_id, t.title]));

  useEffect(() => {
    if (!isOpen) return;

    let cancelled = false;
    setIsLoadingQuestions(true);
    setLoadError(null);
    setQuestions([]);
    setStep("intro");
    setAnswers({});

    api
      .generateQuiz(token, roadmapId, milestone.milestone_id)
      .then((res) => {
        if (cancelled) return;
        if (!res.questions.length) {
          setLoadError("No questions came back for this checkpoint. Try again.");
          return;
        }
        setQuestions(res.questions);
      })
      .catch((err: any) => {
        if (cancelled) return;
        setLoadError(err?.message ?? "Failed to generate this checkpoint's quiz.");
      })
      .finally(() => {
        if (!cancelled) setIsLoadingQuestions(false);
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, milestone.milestone_id]);

  // Results state
  const [scorePercent, setScorePercent] = useState<number>(0);
  const [adaptationSummary, setAdaptationSummary] = useState<string | null>(null);
  const [adaptationChanged, setAdaptationChanged] = useState<boolean>(false);

  if (!isOpen) return null;

  const handleSelectAnswer = (topicId: string, optIdx: number) => {
    setAnswers((prev) => ({ ...prev, [topicId]: optIdx }));
  };

  const calculateResults = () => {
    let correctCount = 0;
    const breakdown: Record<string, number> = {};

    questions.forEach((q) => {
      const selected = answers[q.topic_id];
      const isCorrect = selected === q.correct_index;
      if (isCorrect) {
        correctCount++;
        breakdown[q.topic_id] = 100;
      } else {
        breakdown[q.topic_id] = selected === undefined ? 0 : 33; // minor penalty or completely wrong
      }
    });

    const percent = Math.round((correctCount / questions.length) * 100);
    return { percent, breakdown };
  };

  const handleSubmitQuiz = async () => {
    if (Object.keys(answers).length < questions.length) {
      setError("Please answer all questions before submitting.");
      return;
    }
    setError(null);
    setStep("adapting");
    setIsSubmitting(true);

    const { percent, breakdown } = calculateResults();
    setScorePercent(percent);

    try {
      const response = await api.adaptRoadmap(token, roadmapId, {
        milestoneId: milestone.milestone_id,
        quizId: milestone.checkpoint_quiz_id,
        scorePercent: percent,
        topicBreakdown: breakdown,
      });

      setAdaptationSummary(response.changeSummary);
      setAdaptationChanged(response.changed);
      setStep("results");

      // Notify parent to refresh roadmap
      onAdaptResult(response.changeSummary, response.changed);
    } catch (err: any) {
      setError(err?.message ?? "Failed to submit quiz to adaptive engine.");
      setStep("questions");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReset = () => {
    setStep("intro");
    setAnswers({});
    setError(null);
    setScorePercent(0);
    setAdaptationSummary(null);
    setAdaptationChanged(false);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-bg/85 p-4 backdrop-blur-sm">
      <div className="w-full max-w-lg rounded-lg border border-mist bg-panel p-6 shadow-xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-mist pb-3">
          <div>
            <p className="font-mono-label text-xs uppercase tracking-widest text-blaze">
              Switchbacks
            </p>
            <h2 className="font-display text-2xl font-semibold text-parchment">
              Checkpoint: {milestone.title}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="text-fog hover:text-parchment font-mono-label text-lg p-1"
          >
            ✕
          </button>
        </div>

        {/* Steps */}
        {step === "intro" && (
          <div className="mt-4 space-y-4">
            {isLoadingQuestions && (
              <div className="flex items-center gap-3 py-2">
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-blaze border-t-transparent" />
                <p className="text-xs text-fog font-mono-label">
                  Generating this checkpoint's questions...
                </p>
              </div>
            )}

            {loadError && (
              <p className="text-xs text-blaze font-mono-label bg-blaze/10 border border-blaze/20 rounded p-2">
                ⚠️ {loadError}
              </p>
            )}

            {!isLoadingQuestions && !loadError && (
              <p className="text-sm text-fog">
                Welcome to the checkpoint quiz for <strong className="text-parchment">{milestone.title}</strong>.
                This quiz contains <span className="text-blaze font-semibold font-mono-label">{questions.length} questions</span>.
              </p>
            )}

            <div className="bg-panel-raised p-4 rounded border border-mist text-xs text-fog space-y-2">
              <p className="font-semibold text-parchment">How the adaptive engine works:</p>
              <ul className="list-disc pl-4 space-y-1">
                <li>Score <strong className="text-moss">70% or higher</strong> to clear the milestone and unlock the next stretch.</li>
                <li>Score <strong className="text-blaze">less than 70%</strong>, and the AI Mentor's Adaptive Engine will rewrite your roadmap, adding reinforcement topics or bending the route.</li>
              </ul>
            </div>
            <div className="flex justify-end gap-3 pt-2">
              <button
                onClick={onClose}
                className="rounded-full border border-mist px-4 py-2 text-xs text-fog hover:text-parchment transition"
              >
                Cancel
              </button>
              <button
                onClick={() => setStep("questions")}
                disabled={isLoadingQuestions || !!loadError || questions.length === 0}
                className="rounded-full bg-blaze px-5 py-2 text-xs font-semibold text-bg hover:bg-blaze-dim transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Begin Checkpoint
              </button>
            </div>
          </div>
        )}

        {step === "questions" && (
          <div className="mt-4 space-y-6">
            {questions.map((q, idx) => (
              <div key={q.topic_id} className="space-y-3 border-b border-mist/40 pb-4 last:border-b-0">
                <p className="font-mono-label text-[11px] uppercase tracking-wider text-moss">
                  Question {idx + 1} of {questions.length} • {topicTitleById.get(q.topic_id) ?? q.topic_id}
                </p>
                <p className="text-sm text-parchment font-medium">{q.question}</p>
                <div className="space-y-2">
                  {q.options.map((opt, optIdx) => {
                    const isSelected = answers[q.topic_id] === optIdx;
                    return (
                      <button
                        key={optIdx}
                        type="button"
                        onClick={() => handleSelectAnswer(q.topic_id, optIdx)}
                        className={`w-full text-left p-3 rounded text-xs transition border ${
                          isSelected
                            ? "bg-blaze/10 border-blaze text-parchment"
                            : "bg-panel-raised border-mist text-fog hover:border-fog"
                        }`}
                      >
                        <div className="flex items-start">
                          <span className={`mr-2 h-4 w-4 rounded-full border flex items-center justify-center flex-shrink-0 mt-0.5 ${
                            isSelected ? "border-blaze bg-blaze text-bg text-[10px]" : "border-fog"
                          }`}>
                            {isSelected && "●"}
                          </span>
                          <span>{opt}</span>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            ))}

            {error && (
              <p className="text-xs text-blaze font-mono-label bg-blaze/10 border border-blaze/20 rounded p-2">
                ⚠️ {error}
              </p>
            )}

            <div className="flex justify-between items-center pt-4 border-t border-mist">
              <button
                onClick={() => setStep("intro")}
                className="text-xs text-moss hover:underline"
              >
                ← Back to Intro
              </button>
              <div className="flex gap-2">
                <button
                  onClick={onClose}
                  className="rounded-full border border-mist px-4 py-2 text-xs text-fog hover:text-parchment transition"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSubmitQuiz}
                  disabled={isSubmitting}
                  className="rounded-full bg-blaze px-5 py-2 text-xs font-semibold text-bg hover:bg-blaze-dim transition"
                >
                  {isSubmitting ? "Submitting..." : "Submit Answers"}
                </button>
              </div>
            </div>
          </div>
        )}

        {step === "adapting" && (
          <div className="mt-8 mb-4 text-center space-y-4">
            <div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-blaze border-t-transparent"></div>
            <p className="font-mono-label text-xs uppercase tracking-widest text-blaze">
              AI Adaptation Engine
            </p>
            <p className="text-sm text-fog max-w-xs mx-auto">
              Analyzing answers against mastery tracking, detecting gaps, and adapting route milestones...
            </p>
          </div>
        )}

        {step === "results" && (
          <div className="mt-4 space-y-5">
            <div className="text-center py-4 bg-panel-raised rounded border border-mist">
              <p className="text-xs font-mono-label uppercase tracking-widest text-fog">Quiz Completed</p>
              <h3 className="text-4xl font-display font-semibold mt-1 text-parchment">
                {scorePercent}%
              </h3>
              <p className={`text-xs mt-2 font-mono-label ${scorePercent >= 70 ? "text-moss" : "text-blaze"}`}>
                {scorePercent >= 70 ? "✓ CHECPOINT CLEARED" : "⚠️ REMEDIATION TRIGGERED"}
              </p>
            </div>

            <div className="space-y-2">
              <h4 className="font-mono-label text-xs uppercase tracking-wider text-fog">Engine Action</h4>
              <div className="bg-bg border border-mist rounded p-4 text-sm leading-relaxed">
                {adaptationChanged ? (
                  <div>
                    <span className="inline-block bg-blaze/10 border border-blaze/30 text-blaze font-mono-label text-[10px] rounded px-2 py-0.5 mb-2">
                      ROADMAP ADAPTED
                    </span>
                    <p className="text-parchment">{adaptationSummary}</p>
                  </div>
                ) : (
                  <div>
                    <span className="inline-block bg-moss/10 border border-moss/30 text-moss font-mono-label text-[10px] rounded px-2 py-0.5 mb-2">
                      ROADMAP UNCHANGED
                    </span>
                    <p className="text-fog">
                      {adaptationSummary || "You've successfully cleared this checkpoint. The course continues forward as planned!"}
                    </p>
                  </div>
                )}
              </div>
            </div>

            <div className="flex justify-end gap-3 pt-4 border-t border-mist">
              {scorePercent < 70 && (
                <button
                  onClick={handleReset}
                  className="rounded-full border border-blaze text-blaze px-4 py-2 text-xs font-medium hover:bg-blaze/10 transition"
                >
                  Retry Practice
                </button>
              )}
              <button
                onClick={onClose}
                className="rounded-full bg-blaze px-6 py-2 text-xs font-semibold text-bg hover:bg-blaze-dim transition"
              >
                Return to Trail
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
