import { useState, useEffect } from "react";
import { Topic, LessonContent, api } from "../lib/api";

type TopicStudyModalProps = {
  isOpen: boolean;
  onClose: () => void;
  token: string;
  roadmapId: string;
  topic: Topic;
  allTopics: Topic[];
  onSuccess: (updatedRoadmap: any) => void;
  onOpenLogSession: (topicId: string) => void;
};

export default function TopicStudyModal({
  isOpen,
  onClose,
  token,
  roadmapId,
  topic,
  allTopics,
  onSuccess,
  onOpenLogSession,
}: TopicStudyModalProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [synth, setSynth] = useState<SpeechSynthesis | null>(null);
  const [activeTab, setActiveTab] = useState<"lesson" | "quiz">("lesson");
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Real, domain-aware lesson content generated by mentor_ai_engine —
  // fetched once when the modal opens for this topic. Replaces the old
  // hardcoded fake explanation text + fake JS "sandbox" code block that
  // was shown for every topic regardless of subject matter.
  const [lesson, setLesson] = useState<LessonContent | null>(null);
  const [isLoadingLesson, setIsLoadingLesson] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  // Quiz state
  const [quizAnswers, setQuizAnswers] = useState<Record<number, number>>({});
  const [quizSubmitted, setQuizSubmitted] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined" && window.speechSynthesis) {
      setSynth(window.speechSynthesis);
    }
  }, []);

  // Stop speech when closing or changing topic
  useEffect(() => {
    return () => {
      if (synth) {
        synth.cancel();
      }
    };
  }, [synth, topic]);

  useEffect(() => {
    if (!isOpen || topic.status === "locked") return;

    let cancelled = false;
    setIsLoadingLesson(true);
    setLoadError(null);
    setLesson(null);
    setActiveTab("lesson");
    setQuizAnswers({});
    setQuizSubmitted(false);

    api
      .generateLesson(token, roadmapId, topic.topic_id)
      .then((res) => {
        if (cancelled) return;
        setLesson(res.lesson);
      })
      .catch((err: any) => {
        if (cancelled) return;
        setLoadError(err?.message ?? "Failed to generate this topic's lesson content.");
      })
      .finally(() => {
        if (!cancelled) setIsLoadingLesson(false);
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, topic.topic_id, topic.status]);

  if (!isOpen) return null;

  // Find prerequisite titles
  const prereqTitles = topic.prerequisites
    .map((pid) => allTopics.find((t) => t.topic_id === pid)?.title)
    .filter(Boolean) as string[];

  const handleToggleSpeech = () => {
    if (!synth || !lesson) return;

    if (isPlaying) {
      synth.cancel();
      setIsPlaying(false);
      return;
    }

    const speakText = `Lesson Topic: ${topic.title}. ${topic.description}. Here is an overview of the key concepts. ${lesson.explanation.join(" ")}`;
    const newUtterance = new SpeechSynthesisUtterance(speakText);
    newUtterance.onend = () => setIsPlaying(false);
    newUtterance.onerror = () => setIsPlaying(false);

    // Try to find a pleasant English voice
    const voices = synth.getVoices();
    const naturalVoice = voices.find(
      (v) => v.lang.startsWith("en") && (v.name.includes("Natural") || v.name.includes("Google"))
    );
    if (naturalVoice) newUtterance.voice = naturalVoice;

    setIsPlaying(true);
    synth.speak(newUtterance);
  };

  const handleMarkCompleted = async () => {
    setIsSubmitting(true);
    try {
      // 1. Log a session first to record study time and update mastery
      await api.createSessionLog(token, {
        duration: topic.estimated_hours * 60, // Convert hours to minutes
        topics: [topic.topic_id],
        difficulty: topic.estimated_hours > 4 ? "hard" : "medium",
        notes: `Completed topic study for ${topic.title} in the Interactive Course Player.`,
        roadmapId,
      });

      // 2. Update roadmap status in database
      const res = await api.updateTopicStatus(token, roadmapId, topic.topic_id, "completed");
      onSuccess(res.roadmap);
      onClose();
    } catch (err: any) {
      alert("Failed to mark topic as completed: " + err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleAnswerSelect = (qIdx: number, oIdx: number) => {
    if (quizSubmitted) return;
    setQuizAnswers((prev) => ({ ...prev, [qIdx]: oIdx }));
  };

  const quizQuestions = lesson?.practice_questions ?? [];

  const handleQuizSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (Object.keys(quizAnswers).length < quizQuestions.length) {
      alert("Please answer all questions before submitting.");
      return;
    }
    setQuizSubmitted(true);
  };

  const resetQuiz = () => {
    setQuizAnswers({});
    setQuizSubmitted(false);
  };

  const score = quizQuestions.reduce(
    (acc, q, idx) => (quizAnswers[idx] === q.correct_index ? acc + 1 : acc),
    0
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-bg/85 p-4 backdrop-blur-sm">
      <div className="w-full max-w-3xl rounded-lg border border-mist bg-panel p-6 shadow-xl max-h-[92vh] flex flex-col">
        {/* Header */}
        <div className="flex items-start justify-between border-b border-mist pb-3 shrink-0">
          <div>
            <div className="flex items-center gap-2">
              <span className="font-mono-label text-xs uppercase tracking-widest text-blaze">
                Course Study Player
              </span>
              <span className={`text-[10px] font-mono-label px-2.5 py-0.5 rounded-full border ${
                topic.status === "completed"
                  ? "bg-moss/10 border-moss/30 text-moss"
                  : topic.status === "locked"
                  ? "bg-bg/20 border-mist text-fog"
                  : "bg-blaze/10 border-blaze/30 text-blaze"
              }`}>
                {topic.status === "in_progress" ? "In Progress" : topic.status === "available" ? "Available" : topic.status === "completed" ? "Completed" : "Locked"}
              </span>
            </div>
            <h2 className="font-display text-2xl font-bold text-parchment mt-1">
              {topic.title}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="text-fog hover:text-parchment font-mono-label text-lg p-1 transition"
          >
            ✕
          </button>
        </div>

        {/* Locked View */}
        {topic.status === "locked" ? (
          <div className="flex-grow overflow-y-auto py-8 text-center space-y-4">
            <div className="inline-flex h-16 w-16 items-center justify-center rounded-full bg-mist/20 border border-mist text-fog text-3xl">
              🔒
            </div>
            <h3 className="font-display text-lg font-semibold text-parchment">This course topic is locked</h3>
            <p className="text-sm text-fog max-w-md mx-auto leading-relaxed">
              Before climbing to this point, you must complete the prerequisite topics in the preceding stretches:
            </p>
            {prereqTitles.length > 0 ? (
              <div className="max-w-sm mx-auto bg-bg/40 border border-mist rounded p-3 space-y-1.5 text-xs text-left">
                {prereqTitles.map((title) => (
                  <div key={title} className="flex items-center gap-2 text-fog">
                    <span className="text-blaze text-[10px]">▲</span>
                    <span>{title}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-xs text-blaze font-mono-label">No prerequisite details found</p>
            )}
            <div className="pt-4">
              <button
                onClick={onClose}
                className="rounded-full bg-panel-raised border border-mist hover:border-fog hover:text-parchment px-6 py-2 text-xs font-semibold text-fog transition"
              >
                Back to Map
              </button>
            </div>
          </div>
        ) : (
          /* Active Interactive Study View */
          <>
            {/* Tabs & Controls */}
            <div className="flex items-center justify-between border-b border-mist/40 py-2 shrink-0">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setActiveTab("lesson")}
                  className={`px-4 py-1.5 rounded-full text-xs font-mono-label transition border ${
                    activeTab === "lesson"
                      ? "bg-blaze text-bg border-blaze font-semibold"
                      : "border-transparent text-fog hover:text-parchment hover:border-mist"
                  }`}
                >
                  📖 Interactive Lesson
                </button>
                <button
                  onClick={() => setActiveTab("quiz")}
                  disabled={!lesson}
                  className={`px-4 py-1.5 rounded-full text-xs font-mono-label transition border disabled:opacity-40 disabled:cursor-not-allowed ${
                    activeTab === "quiz"
                      ? "bg-blaze text-bg border-blaze font-semibold"
                      : "border-transparent text-fog hover:text-parchment hover:border-mist"
                  }`}
                >
                  📝 Checkpoint Quiz
                </button>
              </div>

              {/* TTS Narrator */}
              <button
                onClick={handleToggleSpeech}
                disabled={!lesson}
                className={`flex items-center gap-2 rounded-full border px-3 py-1 text-xs transition disabled:opacity-40 disabled:cursor-not-allowed ${
                  isPlaying
                    ? "bg-moss/20 border-moss text-moss"
                    : "bg-panel-raised border-mist text-fog hover:border-blaze hover:text-parchment"
                }`}
                title="Listen to lesson summary"
              >
                <span>{isPlaying ? "⏹️ Pause voice" : "🔊 Narrator voice"}</span>
                {isPlaying && (
                  <span className="flex gap-0.5 items-end h-3">
                    <span className="w-0.5 bg-moss animate-pulse h-1"></span>
                    <span className="w-0.5 bg-moss animate-pulse h-2.5 delay-75"></span>
                    <span className="w-0.5 bg-moss animate-pulse h-2 delay-150"></span>
                  </span>
                )}
              </button>
            </div>

            {/* Scrollable Workspace */}
            <div className="flex-grow overflow-y-auto py-4 pr-1 min-h-[40vh]">
              {isLoadingLesson && (
                <div className="flex items-center justify-center gap-3 py-16">
                  <div className="h-5 w-5 animate-spin rounded-full border-2 border-blaze border-t-transparent" />
                  <p className="text-sm text-fog font-mono-label">Generating this topic's lesson...</p>
                </div>
              )}

              {loadError && !isLoadingLesson && (
                <div className="text-center py-16 space-y-3">
                  <p className="text-sm text-blaze font-mono-label bg-blaze/10 border border-blaze/20 rounded p-3 max-w-md mx-auto">
                    ⚠️ {loadError}
                  </p>
                </div>
              )}

              {!isLoadingLesson && !loadError && lesson && (
                activeTab === "lesson" ? (
                  /* Lesson Tab */
                  <div className="space-y-6">
                    {/* Summary Callout */}
                    <div className="border-l-4 border-blaze bg-blaze/5 p-4 rounded-r">
                      <p className="font-mono-label text-[10px] uppercase text-blaze font-bold tracking-wider">
                        Topic Overview
                      </p>
                      <p className="text-sm text-parchment mt-1 leading-relaxed italic">
                        "{topic.description}"
                      </p>
                    </div>

                    {/* Written Lectures */}
                    <div className="space-y-4 text-sm leading-relaxed text-fog">
                      {lesson.explanation.map((p, idx) => (
                        <p key={idx}>{p}</p>
                      ))}
                    </div>

                    {/* Code Example — only rendered if the topic is genuinely
                        code-related, per has_code_example from real generation */}
                    {lesson.has_code_example && lesson.code_example && (
                      <div className="space-y-2">
                        <p className="font-mono-label text-[10px] uppercase text-moss font-bold tracking-wider">
                          Code Example — {lesson.code_example.language}
                        </p>
                        <pre className="bg-bg/80 border border-mist/60 rounded p-4 text-xs text-moss font-mono overflow-x-auto whitespace-pre leading-relaxed">
                          {lesson.code_example.code}
                        </pre>
                      </div>
                    )}

                    {/* Success Notes if completed */}
                    {topic.status === "completed" && (
                      <div className="border border-moss/40 bg-moss/5 rounded p-4 text-center">
                        <span className="text-moss text-sm font-semibold">🎉 You have already cleared this topic!</span>
                        <p className="text-xs text-fog mt-1">Feel free to review the materials or take the quiz again.</p>
                      </div>
                    )}
                  </div>
                ) : (
                  /* Quiz Tab */
                  <div className="space-y-6">
                    {!quizSubmitted ? (
                      <form onSubmit={handleQuizSubmit} className="space-y-6">
                        {quizQuestions.map((q, qIdx) => (
                          <div key={qIdx} className="space-y-2.5 p-4 border border-mist/40 bg-panel-raised rounded-md">
                            <p className="text-sm font-medium text-parchment">
                              <span className="text-blaze mr-1.5 font-bold">{qIdx + 1}.</span> {q.question}
                            </p>
                            <div className="space-y-2">
                              {q.options.map((opt, oIdx) => {
                                const isSelected = quizAnswers[qIdx] === oIdx;
                                return (
                                  <button
                                    key={oIdx}
                                    type="button"
                                    onClick={() => handleAnswerSelect(qIdx, oIdx)}
                                    className={`w-full text-left p-3 rounded text-xs transition border ${
                                      isSelected
                                        ? "bg-blaze/10 border-blaze text-parchment"
                                        : "bg-panel border-mist/40 text-fog hover:border-fog"
                                    }`}
                                  >
                                    <span className={`inline-block mr-2 text-[10px] font-mono-label px-1.5 py-0.5 rounded border ${
                                      isSelected ? "bg-blaze text-bg border-blaze" : "bg-bg border-mist"
                                    }`}>
                                      {String.fromCharCode(65 + oIdx)}
                                    </span>
                                    {opt}
                                  </button>
                                );
                              })}
                            </div>
                          </div>
                        ))}
                        <div className="flex justify-end pt-2">
                          <button
                            type="submit"
                            className="rounded-full bg-blaze px-6 py-2.5 text-xs font-semibold text-bg hover:bg-blaze-dim transition"
                          >
                            Submit Quiz
                          </button>
                        </div>
                      </form>
                    ) : (
                      /* Quiz Results */
                      <div className="text-center py-6 space-y-6">
                        <div className="inline-flex h-20 w-20 items-center justify-center rounded-full border border-mist bg-panel-raised">
                          <span className="text-2xl font-bold font-mono-label text-blaze">
                            {score}/{quizQuestions.length}
                          </span>
                        </div>
                        <div>
                          <h3 className="font-display text-xl font-bold text-parchment">
                            {score === quizQuestions.length ? "Summit Reached! Perfect Score" : "Almost there!"}
                          </h3>
                          <p className="text-sm text-fog max-w-md mx-auto mt-2">
                            {score === quizQuestions.length
                              ? "Excellent understanding! You've grasped all key concepts for this topic."
                              : "A few answers were incorrect. Review the hints below or study the lesson outline again."}
                          </p>
                        </div>

                        {/* Incorrect Answers Review */}
                        {score < quizQuestions.length && (
                          <div className="max-w-lg mx-auto text-left space-y-3 pt-2">
                            {quizQuestions.map((q, idx) => {
                              const isCorrect = quizAnswers[idx] === q.correct_index;
                              if (isCorrect) return null;
                              return (
                                <div key={idx} className="p-3 border border-red-500/20 bg-red-500/5 rounded text-xs">
                                  <p className="font-semibold text-parchment">Review Question {idx + 1}:</p>
                                  <p className="text-fog italic mt-0.5">"{q.question}"</p>
                                  <p className="text-red-400 mt-1"><strong>Your Answer:</strong> {q.options[quizAnswers[idx]]}</p>
                                  <p className="text-moss mt-0.5"><strong>Correct Answer:</strong> {q.options[q.correct_index]}</p>
                                  <p className="text-fog mt-2 font-mono-label text-[10px] bg-bg/40 border border-mist/30 p-2 rounded">
                                    💡 Hint: {q.hint}
                                  </p>
                                </div>
                              );
                            })}
                          </div>
                        )}

                        <div className="flex justify-center gap-3 pt-4">
                          <button
                            onClick={resetQuiz}
                            className="rounded-full border border-mist px-6 py-2 text-xs font-semibold text-fog hover:text-parchment transition"
                          >
                            Try Again
                          </button>
                          {score === quizQuestions.length && topic.status !== "completed" && (
                            <button
                              onClick={handleMarkCompleted}
                              disabled={isSubmitting}
                              className="rounded-full bg-moss text-bg hover:bg-moss/80 px-6 py-2 text-xs font-semibold transition"
                            >
                              Mark Topic Completed
                            </button>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                )
              )}
            </div>

            {/* Bottom Controls / Actions */}
            <div className="flex items-center justify-between border-t border-mist pt-4 shrink-0">
              <span className="text-[10px] text-fog font-mono-label uppercase">
                Estimated study allocation: {topic.estimated_hours} Hours
              </span>
              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={() => onOpenLogSession(topic.topic_id)}
                  className="rounded-full border border-mist px-4 py-2 text-xs font-medium text-fog hover:text-parchment hover:border-mist transition"
                >
                  ⏱️ Log Custom Session
                </button>
                {topic.status !== "completed" && (
                  <button
                    type="button"
                    onClick={handleMarkCompleted}
                    disabled={isSubmitting}
                    className="rounded-full bg-blaze px-5 py-2 text-xs font-semibold text-bg hover:bg-blaze-dim transition disabled:opacity-50"
                  >
                    {isSubmitting ? "Saving..." : "Mark Completed"}
                  </button>
                )}
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
